[package]
name = "m451-hal"
version = "0.1.0"
authors = ["Sam Day <me@samcday.com>"]
edition = "2018"

[dependencies]
bitfield = "0.13.2"
cortex-m = "0.7.2"
embedded-hal = "1.0.0-alpha.4"
embedded-time = "0.11.0"
heapless = "0.7.0"
m451 = { path = "../pac" }
usb-device = "0.2.8"
